import javax.swing.JOptionPane;

/**
 * Interface Gráfica da Tela de Escolha de Carros e Pistas
 * Código da classe de interface gráfica mais complexo, gerado com o NetBeans
 * Método jButton1ActionPerformed() (evento ao clique do botão) editado manualmente
 * @author Alexandre
 * @version 1.0
 */


public class TelaEscolha extends javax.swing.JFrame {


	private int idPista;
	private int idCarro;
	private Jogo jogo;



	/**
	 * Creates new form TelaEscolha3
	 */
	public TelaEscolha(Jogo j) {
		initComponents();
		jogo = j;	
	}




	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroupCarros = new javax.swing.ButtonGroup();
		buttonGroupPistas = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jRadioButton7 = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setIcon(new javax.swing.ImageIcon("imagens\\jogos-de-carros-de-corrida-9c.JPG")); // NOI18N

		jLabel2.setIcon(new javax.swing.ImageIcon("imagens\\carros.PNG")); // NOI18N

		jLabel3.setIcon(new javax.swing.ImageIcon("imagens\\pistas2.PNG")); // NOI18N

		buttonGroupCarros.add(jRadioButton1);
		jRadioButton1.setText("Carro Nº 0");

		buttonGroupCarros.add(jRadioButton2);
		jRadioButton2.setText("Carro Nº 1");

		buttonGroupCarros.add(jRadioButton3);
		jRadioButton3.setText("Carro Nº 2");

		buttonGroupCarros.add(jRadioButton4);
		jRadioButton4.setText("Carro Nº 3");

		buttonGroupPistas.add(jRadioButton5);
		jRadioButton5.setText("Pista 1");

		buttonGroupPistas.add(jRadioButton6);
		jRadioButton6.setText("Pista 2");

		buttonGroupPistas.add(jRadioButton7);
		jRadioButton7.setText("Pista 3");

		jLabel4.setText("Escolha o Carro:");

		jLabel5.setText("Escolha a pista:");

		jButton1.setText("OK");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabel1)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGap(72, 72, 72)
														.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(layout.createSequentialGroup()
																.addComponent(jLabel2)
																.addGap(18, 18, 18)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jRadioButton1)
																		.addComponent(jRadioButton2)
																		.addComponent(jRadioButton3)
																		.addComponent(jRadioButton4))))
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(layout.createSequentialGroup()
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(layout.createSequentialGroup()
																								.addGap(56, 56, 56)
																								.addComponent(jLabel3)
																								.addGap(18, 18, 18)
																								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(layout.createSequentialGroup()
																												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(jRadioButton5)
																														.addComponent(jRadioButton6)
																														.addComponent(jRadioButton7))
																														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
																														.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
																																.addGap(0, 0, Short.MAX_VALUE)
																																.addComponent(jButton1)))))
																																.addGap(5, 5, 5)))
																																.addContainerGap(23, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel4)
								.addComponent(jLabel5))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
														.addGap(28, 28, 28)
														.addComponent(jRadioButton5)
														.addGap(47, 47, 47)
														.addComponent(jRadioButton6)
														.addGap(54, 54, 54)
														.addComponent(jRadioButton7))
														.addComponent(jLabel2))
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
																		.addGap(20, 20, 20)
																		.addComponent(jRadioButton1)
																		.addGap(37, 37, 37)
																		.addComponent(jRadioButton2)
																		.addGap(40, 40, 40)
																		.addComponent(jRadioButton3)
																		.addGap(39, 39, 39)
																		.addComponent(jRadioButton4))
																		.addComponent(jLabel3)
																		.addComponent(jButton1)))
																		.addContainerGap())
		);

		pack();
	}// </editor-fold>

	/**
	 * Método de evento ao clique do botão
	 * @author Alexandre
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		boolean ok = true;

		if (jRadioButton1.isSelected()){  
			idCarro = 0;	 
		}else if(jRadioButton2.isSelected()){  
			idCarro = 1;
		}else if(jRadioButton3.isSelected()){  
			idCarro = 2;
		}else if(jRadioButton4.isSelected()){  
			idCarro = 3;
		}else {
			ok = false;
		}



		if (jRadioButton5.isSelected()){  
			idPista = 1;	 
		}else if(jRadioButton6.isSelected()){  
			idPista = 2;
		}else if(jRadioButton7.isSelected()){  
			idPista = 3;
		}else ok = false;

		if(ok == false){ // se usuário não clica na pista ou no carro
			JOptionPane.showMessageDialog(null, "Clique na corrida e na pista para jogar!");
			this.dispose(); // fecha a janela
			jogo.carregarTelaEscolha();	// recarrega a Tela		
		}else{ // se usuário clicou corretamente...
			System.out.println(idCarro);
			System.out.println(idPista);			
			jogo.setPista(idPista);
			jogo.setCarro(idCarro);
			this.dispose(); // fecha a janela
			jogo.iniciarCorrida();

		}





	}

	/**
	 * @param args the command line arguments
	 */
	public void iniciarTelaEscolha() {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaEscolha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new TelaEscolha(jogo).setVisible(true);
			}
		});
	}
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroupCarros;
	private javax.swing.ButtonGroup buttonGroupPistas;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JRadioButton jRadioButton6;
	private javax.swing.JRadioButton jRadioButton7;
	// End of variables declaration
}
